### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by openedev** [heiher/libmali-rk3399#1]
I'm trying to build with arm64 cross compiler
$ make 
gcc -O2 -pipe -Wall -Werror -fPIC `pkg-config --cflags libdrm` -shared -Llib -lmali-midgard-t86x-r14p0-gbm -o lib/libgbm.so.1.0.0 src/gbm-wrapper.c
/usr/bin/ld: skipping incompatible lib/libmali-midgard-t86x-r14p0-gbm.so when searching for -lmali-midgard-t86x-r14p0-gbm
/usr/bin/ld: cannot find -lmali-midgard-t86x-r14p0-gbm
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'lib/libgbm.so.1.0.0' failed
make: *** [lib/libgbm.so.1.0.0] Error 1

Any help?

**Comment by heiher** [comment]
You should build with `CROSS_PREFIX`:
```bash
make CROSS_PREFIX=[full path]/aarch64-unknown-gnu-
```

**Comment by heiher** [comment]
and libdrm for aarch64 devel package:
```bash
export PKG_CONFIG_PATH=[path of libdrm pkgconfig directory]
```

**Comment by openedev** [comment]
So, it would require LIBDRM dependency in arm64. Do you have any link to cross-compile that?

**Comment by heiher** [comment]
1. Make working directory and change to.
```bash
mkdir -p workdir/sysroot
cd workdir
```
2. Prepare sysroot.
```bash
wget http://mirror.archlinuxarm.org/aarch64/extra/libdrm-2.4.99-1-aarch64.pkg.tar.xz
tar -xJf libdrm-2.4.99-1-aarch64.pkg.tar.xz -C sysroot
wget http://mirror.archlinuxarm.org/aarch64/extra/mesa-19.1.4-1-aarch64.pkg.tar.xz
tar -xJf mesa-19.1.4-1-aarch64.pkg.tar.xz -C sysroot
export PKG_CONFIG_SYSROOT_DIR=`pwd`/sysroot
```
3. Make gbm warapper.
```bash
git clone https://github.com/heiher/libmali-rk3399
cd libmali-rk3399
make CROSS_PREFIX=aarch64-linux-gnu-
```

**Comment by heiher** [comment]
> So, it would require LIBDRM dependency in arm64. Do you have any link to cross-compile that?

Any issues?
